name: 'Terraform Infrastructure'

on:
  # Gatilho automático ao dar push na main ou na feature branch
  push:
    branches: [ "main", "feature/implement_terraforms" ]

  # Gatilho MANUAL (O "Botão Mágico")
  workflow_dispatch:
    inputs:
      action:
        description: 'Ação do Terraform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_SESSION_TOKEN removido pois você está em conta Real
          AWS_REGION: 'us-east-1'

      # --- PLAN (Roda sempre no apply ou push para validação) ---
      - name: Terraform Plan
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      # --- APPLY (Cria o banco) ---
      - name: Terraform Apply
        # Roda se for Push na Main OU se você escolheu "apply" manualmente
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: terraform apply -var="db_password=${{ secrets.DB_PASSWORD }}" -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      # --- DESTROY (Apaga o banco - CUIDADO!) ---
      - name: Terraform Destroy
        # Só roda se você escolheu explicitamente "destroy" no botão manual
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -var="db_password=${{ secrets.DB_PASSWORD }}" -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'